# Openshift: manifest for static pods are in /etc/origin/node/pods
apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
  labels:
    openshift.io/control-plane: 'true'
  name: kube-keepalived
  namespace: kube-system
spec:
  containers:
  - name: keepalived
    image: docker.io/bsctl/keepalived:1.3
    args: # override the CMD ["-nlPd"] in Dockerfile
    - -nlPdD
    env:
    - name: KEEPALIVED_INTERFACE
      value: 'eth0'
    - name: KEEPALIVED_STATE
      value: 'BACKUP'
    - name: KEEPALIVED_PASSWORD # echo 'password' | base64
      value: 'cGFzc3dvcmQK'
    - name: KEEPALIVED_HEALTH_SERVICE_NAME
      value: 'apiserver'
    - name: KEEPALIVED_HEALTH_SERVICE_INTERVAL
      value: '20'
    - name: KEEPALIVED_HEALTH_SERVICE_TIMEOUT
      value: '5'
    - name: KEEPALIVED_HEALTH_SERVICE_CHECK
      value: '/usr/bin/curl -s -k https://localhost:8443/healthz -o /dev/null'
    - name: KEEPALIVED_HEALTH_SERVICE_USER
      value: 'root'
    - name: KEEPALIVED_ROUTER_ID
      value: '100'
    - name: KEEPALIVED_PRIORITY
      value: ''
    - name: KEEPALIVED_VIRTUAL_IP
      value: '10.10.10.250'
    - name: KEEPALIVED_ADVERT_INT
      value: '3'
    - name: KEEPALIVED_UNICAST_PEER
      value: '10.10.10.10 10.10.10.11 10.10.10.12'       
    livenessProbe:
      exec:
        command: ["pidof", "keepalived"]
      initialDelaySeconds: 10
    securityContext:
      privileged: true
    resources:
    volumeMounts:
    - mountPath: /etc/localtime
      name: host-localtime
  hostNetwork: true
  priorityClassName: system-node-critical
  restartPolicy: Always
  volumes:
  - hostPath:
      path: /etc/localtime
    name: host-localtime
