apiVersion: v1
kind: ConfigMap
metadata:
  name: keepalived-install-scripts
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubelived.labels" . | nindent 4 }}
data:
  install.sh: |
    #!/bin/sh
    #
    echo $(date): "Copying keepalived manifest file to /etc/kubernetes/manifests/kube-keepalived.yaml"
    cp -f /opt/kube-keepalived.yaml /etc/kubernetes/manifests/kube-keepalived.yaml
    chmod 600 /etc/kubernetes/manifests/kube-keepalived.yaml
    #
    echo $(date): "Copying keepalived config file to {{ .Values.keepalived_config_path }}/{{ .Values.keepalived_config_file }}" 
    cp -f /opt/{{ .Values.keepalived_config_file }} {{ .Values.keepalived_config_path }}/{{ .Values.keepalived_config_file }}

    KEEPALIVED_INTERFACE=$(ip route get {{ .Values.keepalived_virtual_address }} | awk '{print $3}')
    echo $(date): "Finding the keepalived interface:" $KEEPALIVED_INTERFACE 
    KEEPALIVED_PRIORITY=$(ip route get {{ .Values.keepalived_virtual_address }} | awk '{print $5}' | cut -d. -f4)
    echo $(date): "Calculating the keepalived priority:" $KEEPALIVED_PRIORITY

    sed -i "s|KEEPALIVED_INTERFACE|$KEEPALIVED_INTERFACE|g" {{ .Values.keepalived_config_path }}/{{ .Values.keepalived_config_file }}
    sed -i "s|KEEPALIVED_PRIORITY|$KEEPALIVED_PRIORITY|g" {{ .Values.keepalived_config_path }}/{{ .Values.keepalived_config_file }}
    echo $(date): "Updated the keepalived config file"

    # Unless told otherwise, sleep forever.
    # This prevents Kubernetes from restarting the pod repeatedly.
    should_sleep=true
    echo $(date): "Done installing keepalived."
    while [ "$should_sleep" = "true"  ]; do
      if [ -e {{ .Values.keepalived_config_path }}/{{ .Values.keepalived_config_file }} ];
      then
        echo $(date): "Nothing to do, going to sleep again ..."
        sleep 120
      else
        should_sleep=false
        echo $(date): "Missing keepalived configuration file: {{ .Values.keepalived_config_path }}/{{ .Values.keepalived_config_file }}"
      fi
    done
  uninstall.sh: |
    #!/bin/sh
    #
    echo $(date): "Removing keepalived manifest file from /etc/kubernetes/manifests/kube-keepalived.yaml"
    rm -rf /etc/kubernetes/manifests/kube-keepalived.yaml
    echo $(date): "Removing keepalived config file from {{ .Values.keepalived_config_path }}/{{ .Values.keepalived_config_file }}"
    rm -rf {{ .Values.keepalived_config_path }}/{{ .Values.keepalived_config_file }}