apiVersion: v1
kind: ConfigMap
metadata:
  name: keepalived-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubelived.labels" . | nindent 4 }}
data:
  {{ .Values.keepalived.config_file }}: |
    # keepalived global configuration
    global_defs {
      default_interface KEEPALIVED_INTERFACE
      enable_script_security 
    }
    vrrp_script {{ .Values.keepalived.health_service_name }} {
      script   {{ quote .Values.keepalived.health_service_check }}
      interval {{ .Values.keepalived.health_service_interval }}
      timeout  {{ .Values.keepalived.health_service_timeout }}
      rise     {{ .Values.keepalived.health_service_rise }}
      fall     {{ .Values.keepalived.health_service_fall }}
      user     {{ .Values.keepalived.health_service_user }}
    }
    {{- range $key, $val := .Values.keepalived.instances }}
    vrrp_instance {{ $val.iface }} {
      state {{ upper $val.initial_state }}
      interface {{ $val.interface }}
      virtual_router_id {{ $val.router_id }}
      priority KEEPALIVED_PRIORITY
      advert_int {{ $val.health_service_interval }}
      authentication {
        auth_type PASS
        auth_pass {{ $val.password | b64enc }}
      }
      track_script {
        {{ $val.health_service_name }}
      }     
      virtual_ipaddress {
        {{ $val.virtual_address }} label {{ $val.interface }}:VIP
      }
      
      {{- if $val.unicast_peers }}
      unicast_peer {
      {{- range $val.unicast_peers }}
        {{ . }}
      {{- end }}
      }    
      {{- end }}
    }
    {{- end }}
