# Default values for kubelived.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: bsctl/keepalived 
  pullPolicy: IfNotPresent
  tag: ''

installer:
  repository: busybox
  pullPolicy: IfNotPresent
  tag: latest

serviceAccount:
  create: false
  annotations: {}
  name: ''

keepalived_config_path: '/etc/keepalived'
keepalived_config_file: 'keepalived.conf'
keepalived_initial_state: 'backup'
keepalived_password: 'password'
keepalived_health_service_name: 'apiserver'
keepalived_health_service_check: '/usr/bin/curl -s -k https://localhost:6443/healthz -o /dev/null'
keepalived_health_service_user: 'root'
keepalived_health_service_interval: '20'
keepalived_health_service_timeout: '5'
keepalived_health_service_rise: '1'
keepalived_health_service_fall: '1'
keepalived_router_id: '100'
keepalived_advertisement_interval: '3'
keepalived_virtual_address: '10.10.10.250'
keepalived_unicast_peers: []
